### ISSUE TITLE
[doc] what journals seem relevant to this? 

### ISSUE THREAD

**Issue by isabelizimm** [isabelizimm/mlops-metaanalysis#11]
- JOSS??? idk if they really take stuff like this
- https://analyticsindiamag.com/10-essential-academic-journals-data-scientists/

**Comment by isabelizimm** [comment]
look at literature review, see where they are published.

**Comment by reisanar** [comment]
Besides several conference proceedings, the journals below could be explored (need to confirm _aims and scope_, check recent published articles, submission guidelines and timelines, etc.)

1. Journal of Systems and Software. [Link](https://www.sciencedirect.com/journal/journal-of-systems-and-software/about/aims-and-scope)
1. Journal of Software: Evolution and Process. [Link](https://onlinelibrary.wiley.com/page/journal/20477481/homepage/productinformation.html)
1. Information and Software Technology [Link](https://www.sciencedirect.com/journal/information-and-software-technology/about/aims-and-scope)

**Comment by reisanar** [comment]
> 

A couple of other pieces of work to check out: 
 - Teaching MLOps in Higher Education through Project-Based Learning. See <https://arxiv.org/pdf/2302.01048.pdf>
 - The State of MLOps (this was a thesis project in 2021 for a systems engineering student): See <https://repositorio.uniandes.edu.co/bitstream/handle/1992/51495/23642.pdf?sequence=1&isAllowed=y>

**Comment by reisanar** [comment]
Accepted for [IEEE ICMLA](https://www.icmla-conference.org/icmla23/callforpapers.html) 2023 🎉
