### ISSUE TITLE
determine what is considered as an oss tool for this project

### ISSUE THREAD

**Issue by isabelizimm** [isabelizimm/mlops-metaanalysis#7]
in order to be considered an open source project:

- has an [OSI license](https://opensource.org/licenses)
- has at least one open issue (probably not a strong criteria)
- is public

later: think of removing
- lists such as "awesome mlops" esque repos? reasons for keeping: maybe they should be considered their own section, as enablement for the community
- school projects (will probably be at least partially removed with no license?)

**Comment by Nibronix** [comment]
Open source projects are software projects where the source code is publicly available for anyone to use, modify, and distribute without restrictions or cost.

**Comment by isabelizimm** [comment]
> Open source projects are software projects where the source code is publicly available for anyone to use, modify, and distribute without restrictions or cost.

Hey, thank you for the contribution! I added context to this issue: the idea is to create a list of criteria to determine an "open source tool used for MLOps tasks" vs "open sourced code on the topic of MLOps." I added a few ideas to close this issue initially, but happy to collect any other thoughts you might have 🙌
